Repository fun-eat/design-system, pull requests merged in 2023-07, with the labels that each got.

#10 feat: 글로벌 스타일 적용
  .babelrc.json
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  src/FunEatProvider.tsx
  src/index.ts
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
  webpack.config.js
  yarn.lock
Labels: ✨ Feature

#20 chore: import 순서를 관리하는 lint 추가
  .eslintrc.js
  package.json
  yarn.lock
Labels: ⚙️ Chore

#22 chore: css props 추가를 위한 babel plugin 및 타입 추가
  .babelrc.json
  package.json
  src/styles/styled.d.ts
  src/styles/theme.ts
  yarn.lock
Labels: ⚙️ Chore

#13 feat: divider 디자인 시스템 구현
  src/Divider/Divider.stories.tsx
  src/Divider/Divider.tsx
  src/Divider/index.ts
Labels: ✨ Feature, 🎨 UI

#14 feat: Badge 컴포넌트 추가
  src/Badge/Badge.stories.tsx
  src/Badge/Badge.tsx
  src/Badge/index.ts
  src/types.ts
Labels: ✨ Feature, 🎨 UI

#15 feat: Spacing 컴포넌트 추가
  src/Spacing/Spacing.stories.tsx
  src/Spacing/Spacing.tsx
  src/Spacing/index.ts
Labels: ✨ Feature, 🎨 UI

#16 feat: BottomSheet 컴포넌트 추가
  src/BottomSheet/BottomSheet.stories.tsx
  src/BottomSheet/BottomSheet.tsx
  src/BottomSheet/index.ts
  src/styles/animations.ts
Labels: ✨ Feature, 🎨 UI

#17 feat: Button 컴포넌트 추가
  src/Button/Button.stories.tsx
  src/Button/Button.tsx
  src/Button/index.ts
  src/styles/theme.ts
Labels: ✨ Feature, 🎨 UI

#18 feat: Text 컴포넌트 추가
  .eslintrc.js
  src/FunEatProvider.tsx
  src/Text/Text.stories.tsx
  src/Text/Text.tsx
  src/Text/index.ts
  src/type.ts
Labels: ✨ Feature, 🎨 UI

#24 refactor: 컨벤션 맞추기
  src/Badge/Badge.tsx
  src/BottomSheet/BottomSheet.tsx
  src/Button/Button.tsx
  src/Divider/Divider.stories.tsx
  src/Spacing/Spacing.stories.tsx
  src/Spacing/Spacing.tsx
  src/Text/Text.tsx
  src/index.ts
  src/styles/styled.d.ts
  src/type.ts
  src/types.ts
Labels: 🔧 Refactor

#26 v0.1.0
  .eslintrc.js
  .npmignore
  README.md
  package.json
  src/Badge/Badge.stories.tsx
  src/Badge/Badge.tsx
  src/BottomSheet/BottomSheet.tsx
  src/Button/Button.tsx
  src/FunEatProvider.tsx
  src/Spacing/Spacing.stories.tsx
  src/Text/Text.tsx
  src/index.ts
  tsconfig.json
Labels: 🏠 Build

#30 feat: theme export문 추가
  package.json
  src/hooks/useTheme.ts
  src/index.ts
  src/styled.d.ts
  src/styles/theme.ts
  tsconfig.json
Labels: ✨ Feature, 🐛 Bug

#31 feat: Heading 컴포넌트 추가
  README.md
  src/Heading/Heading.stories.tsx
  src/Heading/Heading.tsx
  src/Heading/index.ts
  src/Text/Text.tsx
  src/styles/theme.ts
Labels: ✨ Feature, 🎨 UI

#37 feat: Checkbox 컴포넌트 추가
  src/Checkbox/Checkbox.stories.tsx
  src/Checkbox/Checkbox.tsx
  src/Checkbox/index.ts
  src/index.ts
Labels: 🎨 UI

#38 feat: Textarea 컴포넌트 추가
  src/Textarea/Textarea.stories.tsx
  src/Textarea/Textarea.tsx
  src/Textarea/index.ts
  src/index.ts
  src/styles/theme.ts
Labels: 🎨 UI

#42 feat: Badge 컴포넌트를 div에서 span태그로 변경
  src/Badge/Badge.tsx
Labels: 🔧 Refactor

#44 refactor: bottom sheet maxWidth 받도록 수정
  src/BottomSheet/BottomSheet.tsx
  src/styles/animations.ts
Labels: 🔧 Refactor

#46 Bottom Sheet 수정
  src/BottomSheet/BottomSheet.stories.tsx
  src/BottomSheet/BottomSheet.tsx
  src/BottomSheet/index.ts
  src/BottomSheet/useBottomSheet.ts
  src/index.ts
Labels: 🔧 Refactor

#47 Button 컴포넌트 수정
  README.md
  src/Button/Button.stories.tsx
  src/Button/Button.tsx
Labels: 🔧 Refactor

#49 Bottom Sheet max height 설정과 y축 스크롤 생성
  src/BottomSheet/BottomSheet.tsx
Labels: 🔧 Refactor

#51 chore: 배포 및 릴리즈 노트 yml 작성
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: ⚙️ Chore

#53 fix: 버튼 props 이름 수정
  README.md
  src/Button/Button.stories.tsx
  src/Button/Button.tsx
Labels: 🐛 Bug
